### ISSUE TITLE
Merge James Work Into ribudget_sankey Repo

### ISSUE THREAD

**Issue by theryankelly** [codeisland/OLD-ribudget_sankey#2]
"I have started a repo for the snakey at
https://github.com/jamesrhaley/snakey."

Let's move this into this code island ribudget_sankey repo

**Comment by nelsonri72** [comment]
@jamesrhaley Shall we send the Sankey github in your domainto Code Island github domain?

**Comment by nelsonri72** [comment]
@jamesrhaley Shall we place the Sankey github in your domain (https://github.com/jamesrhaley/sankey)
to 
codeisland/ribudget_sankey
 github domain?

**Comment by jamesrhaley** [comment]
@nelsonri72 Yes, so now that I have access can I push to it myself?

**Comment by nelsonri72** [comment]
May close. Merged to https://github.com/codeisland/RI-Budget-Sankey
