### ISSUE TITLE
Fill out Budget Visualization project profile webform

### ISSUE THREAD

**Issue by goldenmeanie** [codeisland/OLD-ribudget_sankey#6]
We'd like to feature this project on the website with more detail than the brief summary that is there right now. Fill out this form to help us out

https://docs.google.com/forms/d/1BvsQ01SyRuVVXJYu48QeMkYeuQZEhVWpSVmTYnpx98c/viewform

**Comment by nelsonri72** [comment]
Get input/review from @jamesrhaley https://docs.google.com/document/d/1MD58MnZN8B4joUNTgtieinR0YaECTFIeX6K_2n4nhEY/edit?usp=sharing

**Comment by nelsonri72** [comment]
May close. Issue moved to https://github.com/codeisland/RI-Budget-Sankey/issues/4
